# Video 19

In [2]:
import numpy as np

In [3]:
A = np.arange(1,6)

In [4]:
C = np.arange(1,26).reshape(5,5)

In [6]:
A

array([1, 2, 3, 4, 5])

In [5]:
C

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [7]:
A[2]

3

In [8]:
C[2,3]

14

In [9]:
A[2] = -3

In [10]:
C[2,3] = -14

In [11]:
A

array([ 1,  2, -3,  4,  5])

In [12]:
C

array([[  1,   2,   3,   4,   5],
       [  6,   7,   8,   9,  10],
       [ 11,  12,  13, -14,  15],
       [ 16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25]])

In [13]:
C[2]

array([ 11,  12,  13, -14,  15])

In [14]:
C[4]

array([21, 22, 23, 24, 25])

In [15]:
C[-1]

array([21, 22, 23, 24, 25])

In [20]:
C[-1]= [0,0,0,0,0]

In [21]:
C

array([[  1,   2,   3,   4,   5],
       [  6,   7,   8,   9,  10],
       [ 11,  12,  13, -14,  15],
       [ 16,  17,  18,  19,  20],
       [  0,   0,   0,   0,   0]])

In [22]:
C[-1] =2

In [23]:
C

array([[  1,   2,   3,   4,   5],
       [  6,   7,   8,   9,  10],
       [ 11,  12,  13, -14,  15],
       [ 16,  17,  18,  19,  20],
       [  2,   2,   2,   2,   2]])

In [24]:
C[0:3,2]

array([ 3,  8, 13])

In [25]:
C[2,0:3]

array([11, 12, 13])

In [28]:
C[1,1:3]

array([7, 8])

In [29]:
C[0:4,0]

array([ 1,  6, 11, 16])

In [30]:
C[1:5,0]

array([ 6, 11, 16,  2])

In [31]:
C[1:,0]

array([ 6, 11, 16,  2])

In [32]:
C[1:3,2:4]

array([[  8,   9],
       [ 13, -14]])

In [34]:
C[0:5:2,0:5:2]

array([[ 1,  3,  5],
       [11, 13, 15],
       [ 2,  2,  2]])

In [35]:
C[::2,::2]

array([[ 1,  3,  5],
       [11, 13, 15],
       [ 2,  2,  2]])

In [36]:
C[1::2,::2]

array([[ 6,  8, 10],
       [16, 18, 20]])

In [37]:
C[::3,1::3]

array([[ 2,  5],
       [17, 20]])

In [38]:
C[::4,1:4]

array([[2, 3, 4],
       [2, 2, 2]])

In [39]:
# Assignment
'''1. A = array([12, 15, 18, 21])
 How do we access the element 18 from the given array A? 
2. B = array ( [ [10, 11, 12, 13],
 [20, 21, 22, 23],
 [30, 31, 32, 33],
 [40, 41, 42, 43] ] )
How do we obtain the elements [[21, 22], [31, 32]] from the given array B'''



'1. A = array([12, 15, 18, 21])\n How do we access the element 18 from the given array A? \n2. B = array ( [ [10, 11, 12, 13],\n [20, 21, 22, 23],\n [30, 31, 32, 33],\n [40, 41, 42, 43] ] )\nHow do we obtain the elements [[21, 22], [31, 32]] from the given array B'

In [41]:
A = np.array([12, 15, 18, 21])
B = np.array ( [ [10, 11, 12, 13],
 [20, 21, 22, 23],
 [30, 31, 32, 33],
 [40, 41, 42, 43] ] )

In [42]:
A[2]

18

In [43]:
B[1:3,1:3]

array([[21, 22],
       [31, 32]])