# Video 21

In [23]:
from numpy import matrix

In [24]:
m1 = matrix([[1,2,3,4]])


In [25]:
m1.shape

(1, 4)

In [27]:
l1 = [[1,2,3,4],[5,6,7,8]]
m2 = matrix(l1)
print(m2)

[[1 2 3 4]
 [5 6 7 8]]


In [29]:
from numpy import asmatrix,arange
m2_array = asmatrix(arange(1,9).reshape(2,4))
m2_array

matrix([[1, 2, 3, 4],
        [5, 6, 7, 8]])

In [33]:
m3 = asmatrix(arange(5,13).reshape(2,4))
m3

matrix([[ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])

In [34]:
m3 + m2

matrix([[ 6,  8, 10, 12],
        [14, 16, 18, 20]])

In [35]:
m3-m2

matrix([[4, 4, 4, 4],
        [4, 4, 4, 4]])

In [36]:
6.5*m2

matrix([[ 6.5, 13. , 19.5, 26. ],
        [32.5, 39. , 45.5, 52. ]])

In [37]:
m2.shape

(2, 4)

In [38]:
m4 = asmatrix(arange(1,9).reshape(4,2))

In [39]:
m4.shape

(4, 2)

In [41]:
m2*m4

matrix([[ 50,  60],
        [114, 140]])

In [42]:
print(m4)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [43]:
print(m4.T)

[[1 3 5 7]
 [2 4 6 8]]


In [46]:
from numpy.linalg import det
m5 = matrix([[2,-3,1],[2,0,-1],[1,4,5]])

In [47]:
det(m5)

49.000000000000014

In [48]:
from numpy.linalg import inv
im5 = inv(m5)

In [49]:
im5

matrix([[ 0.08163265,  0.3877551 ,  0.06122449],
        [-0.2244898 ,  0.18367347,  0.08163265],
        [ 0.16326531, -0.2244898 ,  0.12244898]])

In [50]:
from numpy import eye,allclose

In [54]:
allclose(im5*m5,asmatrix(eye(3))) # multiplies the imvetse with the original and them compares with the identity matrix
# allclose compares the elemnt array wise

True

In [57]:
help('numpy.eye')

Help on function eye in numpy:

numpy.eye = eye(N, M=None, k=0, dtype=<class 'float'>, order='C')
    Return a 2-D array with ones on the diagonal and zeros elsewhere.
    
    Parameters
    ----------
    N : int
      Number of rows in the output.
    M : int, optional
      Number of columns in the output. If None, defaults to `N`.
    k : int, optional
      Index of the diagonal: 0 (the default) refers to the main diagonal,
      a positive value refers to an upper diagonal, and a negative value
      to a lower diagonal.
    dtype : data-type, optional
      Data-type of the returned array.
    order : {'C', 'F'}, optional
        Whether the output should be stored in row-major (C-style) or
        column-major (Fortran-style) order in memory.
    
        .. versionadded:: 1.14.0
    
    Returns
    -------
    I : ndarray of shape (N,M)
      An array where all elements are equal to zero, except for the `k`-th
      diagonal, whose values are equal to one.
    
    See Also


In [59]:
''' Given a square matrix A
*eig(A)[0] gives its eigen values
*eig(A)[1] gives its eigen vector
*eigvals(A) gives its eigen values
'''


' Given a square matrix A\n*eig(A)[0] gives its eigen values\n*eig(A)[1] gives its eigen vector\n*eigvals(A) gives its eigen values\n'

In [62]:
from numpy import diag
from numpy.linalg import eig
m6 = asmatrix(diag((1,2,3)))

In [63]:
eig(m6)

(array([1., 2., 3.]),
 matrix([[1., 0., 0.],
         [0., 1., 0.],
         [0., 0., 1.]]))

In [64]:
eig_value = eig(m6)[0]

In [65]:
eig_value

array([1., 2., 3.])

In [66]:
eig_vectors = eig(m6)[1]


In [67]:
eig_vectors

matrix([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [68]:
from numpy.linalg import eigvals
eig_value1 = eigvals(m6)

In [69]:
eig_value1

array([1., 2., 3.])

In [71]:
'''1. A and B are two matrix objects of appropriate sizes. Matrix multiplication is done by
➢ A * B # Ans
➢ multiply(A, B)
➢ mul(A, B)
➢ element_multiply(A,B)
2. eig(A) [1] and eigvals(A) are the same.
➢ True
➢ False # Ans
'''

'1. A and B are two matrix objects of appropriate sizes. Matrix multiplication is done by\n➢ A * B # Ans\n➢ multiply(A, B)\n➢ mul(A, B)\n➢ element_multiply(A,B)\n2. eig(A) [1] and eigvals(A) are the same.\n➢ True\n➢ False # Ans\n'