# Video 17

In [2]:
import numpy as np

In [4]:
L = np.loadtxt("student_record.txt",usecols=(3,4,5,6,7),delimiter=';')

In [5]:
L

array([[53., 36., 28., 16., 44.],
       [58., 37., 42., 35., 40.],
       [72., 56., 71., 55., 70.],
       ...,
       [49., 39., 12., 20., 24.],
       [33., 36., 22., 15., 35.],
       [17., 14., 15., 14., 20.]])

In [9]:
L.shape

(185667, 5)

In [10]:
L[0]

array([53., 36., 28., 16., 44.])

In [12]:
totalmarks = sum(L[0])

In [13]:
totalmarks

177.0

In [14]:
totalmarks/len(L[0])

35.4

In [15]:
np.mean(L[0])

35.4

In [17]:
np.mean(L,0)

array([73.55452504, 53.79828941, 62.83342759, 50.69806158, 63.17056881])

In [18]:
L[:,0]

array([53., 58., 72., ..., 49., 33., 17.])

In [19]:
np.mean(L[:,:])

60.81097448658081

In [20]:
np.median(L[:,0])

76.0

In [21]:
np.median(L,0)

array([76., 53., 62., 49., 64.])

In [22]:
np.std(L[:,0])

14.149386756586962

In [23]:
np.std(L,0)

array([14.14938676, 15.40067866, 23.49972527, 20.06422781, 16.94574819])

In [24]:
football = np.loadtxt("football.txt",usecols =[1,2],delimiter = ',')

In [25]:
football

array([[86., 67.],
       [34., 65.],
       [45., 41.],
       [23., 24.],
       [43., 45.],
       [65., 34.]])

In [38]:
np.sum(football,1)

array([153.,  99.,  86.,  47.,  88.,  99.])

In [39]:
np.median(football,0)

array([44., 43.])

In [40]:
np.median(football,1)

array([76.5, 49.5, 43. , 23.5, 44. , 49.5])

In [42]:
np.std(football,0)

array([20.72572208, 15.57776193])

In [43]:
np.std(football,1)

array([ 9.5, 15.5,  2. ,  0.5,  1. , 15.5])

In [ ]:
# Assignment
'''1. Given a two dimensional list as, two_dimensional_list=[[3,5,8,2,1],[4,3,6,2,1]]
 How do you calculate the mean of each row?
2. Calculate the median of the given list. 
 student_marks=[74,78,56,87,91,82]
3. There is a file with 6 columns. But we want to load text only from columns 2, 3, 4, 5.
 How do we specify that?'''



In [49]:
#1
two_dimensional_list=[[3,5,8,2,1],[4,3,6,2,1]]
np.mean(two_dimensional_list,1)

array([3.8, 3.2])

In [51]:
#2 
student_marks=[74,78,56,87,91,82]
np.median(student_marks)

80.0

In [ ]:
#3
# use parameter usecols = [2,3,4,5]