# Video 18

In [1]:
import numpy as np

In [4]:
a1 = np.array([1,2,3,4])

In [5]:
a1

array([1, 2, 3, 4])

In [49]:
a2 = np.array([[1,2,3,4],[5,6,7,8]])

In [50]:
a2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [51]:
ar = np.arange(1,9)

In [52]:
print(ar)

[1 2 3 4 5 6 7 8]


In [53]:
ar.reshape(2,4)

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [54]:
ar

array([1, 2, 3, 4, 5, 6, 7, 8])

In [55]:
ar.shape=(2,4)

In [56]:
ar

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [57]:
a2.shape

(2, 4)

In [58]:
a1.shape

(4,)

In [59]:
ar.shape

(2, 4)

In [60]:
a3 = np.array([1,2,3,'a string'])

In [61]:
a3 # We do not get error as every element is converted to string

array(['1', '2', '3', 'a string'], dtype='<U11')

In [62]:
np.identity(2)

array([[1., 0.],
       [0., 1.]])

In [63]:
np.zeros((4,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [64]:
a1

array([5, 6, 7, 8])

In [65]:
a1*2

array([10, 12, 14, 16])

In [66]:
a1 +2

array([ 7,  8,  9, 10])

In [67]:
a1

array([5, 6, 7, 8])

In [68]:
a1+=2

In [69]:
a1

array([ 7,  8,  9, 10])

In [70]:
a2 = np.array([5,6,7,8])

In [71]:
a1+a2

array([12, 14, 16, 18])

In [72]:
a1*a2

array([35, 48, 63, 80])

In [73]:
# 1. x = np.array ([1, 2, 3], [5, 6, 7]) is a valid statement? 
#➢ Fallse
# one more square braket will be present

In [74]:
np.zeros_like(0)

array(0)

In [75]:
np.ones(8)

array([1., 1., 1., 1., 1., 1., 1., 1.])

In [36]:
np.ones_like(2)

array(1)