# Video 22

In [1]:
# flatten() returns a copy of the array collapsed into one dimension
# it can be used to convert a multidimensional matrix into a single dimension matrix

In [4]:
from numpy import asmatrix,arange
a = asmatrix(arange(1,10).reshape(3,3))

In [5]:
a

matrix([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [7]:
a.flatten()

matrix([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [8]:
# froenius norm of a matrix
# it is defined as the square root of the sum of the absoulte squares of the elements

In [11]:
#m= [[ 1, 0, 3, 4],
# [ 5, 6, 7, 0],
# [ 9, 10, 11, 12],
# [13, 14, 15, 16]]

m= asmatrix(arange(1,17).reshape(4,4))

In [14]:
m[0,1] =0

In [15]:
m[1,3] = 0

In [16]:
m

matrix([[ 1,  0,  3,  4],
        [ 5,  6,  7,  0],
        [ 9, 10, 11, 12],
        [13, 14, 15, 16]])

In [18]:
from numpy.linalg import inv, norm
im = inv(m)
norm(im)

3.7059917700933944

In [19]:
# infinity norm
# it is defined as the maximum value of sum of the absolute value of elements in each row

In [22]:
#help('numpy.linalg')
'''DESCRIPTION
    Core Linear Algebra Tools
    -------------------------
    Linear algebra basics:
    
    - norm            Vector or matrix norm
    - inv             Inverse of a square matrix
    - solve           Solve a linear system of equations
    - det             Determinant of a square matrix
    - lstsq           Solve linear least-squares problem
    - pinv            Pseudo-inverse (Moore-Penrose) calculated using a singular
                      value decomposition
    - matrix_power    Integer power of a square matrix
    
    Eigenvalues and decompositions:
    
    - eig             Eigenvalues and vectors of a square matrix
    - eigh            Eigenvalues and eigenvectors of a Hermitian matrix
    - eigvals         Eigenvalues of a square matrix
    - eigvalsh        Eigenvalues of a Hermitian matrix
    - qr              QR decomposition of a matrix
    - svd             Singular value decomposition of a matrix
    - cholesky        Cholesky decomposition of a matrix
    
    Tensor operations:
    
    - tensorsolve     Solve a linear tensor equation
    - tensorinv       Calculate an inverse of a tensor
    
    Exceptions:
    
    - LinAlgError     Indicates a failed linear algebra operation
''' 

'DESCRIPTION\n    Core Linear Algebra Tools\n    -------------------------\n    Linear algebra basics:\n    \n    - norm            Vector or matrix norm\n    - inv             Inverse of a square matrix\n    - solve           Solve a linear system of equations\n    - det             Determinant of a square matrix\n    - lstsq           Solve linear least-squares problem\n    - pinv            Pseudo-inverse (Moore-Penrose) calculated using a singular\n                      value decomposition\n    - matrix_power    Integer power of a square matrix\n    \n    Eigenvalues and decompositions:\n    \n    - eig             Eigenvalues and vectors of a square matrix\n    - eigh            Eigenvalues and eigenvectors of a Hermitian matrix\n    - eigvals         Eigenvalues of a square matrix\n    - eigvalsh        Eigenvalues of a Hermitian matrix\n    - qr              QR decomposition of a matrix\n    - svd             Singular value decomposition of a matrix\n    - cholesky        Choles

In [23]:
from numpy import inf
norm(im,ord=inf)


4.624999999999995

In [25]:
help('numpy.linalg.norm')

Help on function norm in numpy.linalg:

numpy.linalg.norm = norm(x, ord=None, axis=None, keepdims=False)
    Matrix or vector norm.
    
    This function is able to return one of eight different matrix norms,
    or one of an infinite number of vector norms (described below), depending
    on the value of the ``ord`` parameter.
    
    Parameters
    ----------
    x : array_like
        Input array.  If `axis` is None, `x` must be 1-D or 2-D.
    ord : {non-zero int, inf, -inf, 'fro', 'nuc'}, optional
        Order of the norm (see table under ``Notes``). inf means numpy's
        `inf` object.
    axis : {int, 2-tuple of ints, None}, optional
        If `axis` is an integer, it specifies the axis of `x` along which to
        compute the vector norms.  If `axis` is a 2-tuple, it specifies the
        axes that hold 2-D matrices, and the matrix norms of these matrices
        are computed.  If `axis` is None then either a vector norm (when `x`
        is 1-D) or a matrix norm (when 

In [26]:
# Single Value Decomposition(SVD)
# the svd is factorization of a real or complex matrix

In [27]:
from numpy.linalg import svd
from numpy import matrix
m1 = matrix([[3,2,2],[2,3,-2]])
U,sigma,V_conjugate = svd(m1)

In [28]:
U


matrix([[-0.70710678, -0.70710678],
        [-0.70710678,  0.70710678]])

In [29]:
sigma


array([5., 3.])

In [30]:
V_conjugate

matrix([[-7.07106781e-01, -7.07106781e-01, -5.55111512e-17],
        [-2.35702260e-01,  2.35702260e-01, -9.42809042e-01],
        [-6.66666667e-01,  6.66666667e-01,  3.33333333e-01]])

In [31]:
from numpy import diag,allclose
from numpy.matlib import zeros
smat = zeros((2,3))

In [32]:
smat

matrix([[0., 0., 0.],
        [0., 0., 0.]])

In [33]:
smat[:2,:2] = diag(sigma)

In [34]:
smat

matrix([[5., 0., 0.],
        [0., 3., 0.]])

In [35]:
allclose(m1,U*smat*V_conjugate)

True

In [37]:
norm(a,ord='fro')

16.881943016134134

In [38]:
norm(a)

16.881943016134134

In [39]:
'''1. norm(A,ord='fro') is the same as norm (A) ?
➢ True # Ans # fro stands for frobenius norm
➢ False
'''

"1. norm(A,ord='fro') is the same as norm (A) ?\n➢ True # Ans # fro stands for frobenius norm\n➢ False\n"